# Stage 1: Build stage
FROM python:3.10-slim as builder

# Cài đặt các gói hệ thống cần thiết cho build
RUN apt-get update && apt-get install -y --no-install-recommends libgl1 && rm -rf /var/lib/apt/lists/*
# Xóa các tệp tin danh sách gói để giảm dung lượng container
RUN rm -rf /var/lib/apt/lists/*
# Đặt thư mục làm việc trong container
WORKDIR /app

# Sao chép requirements.txt và cài đặt dependencies
COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

# Sao chép mã nguồn vào container (ở giai đoạn build)
COPY . /app

# Stage 2: Final stage
FROM python:3.10-slim

# Cài đặt lại libgl1 cho OpenCV (nếu cần)
RUN apt-get update && apt-get install -y --no-install-recommends libgl1 && rm -rf /var/lib/apt/lists/*
# Đặt thư mục làm việc trong container
WORKDIR /app

# Sao chép các thư viện và mã nguồn từ giai đoạn builder
COPY --from=builder /app /app
COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages

# Mở cổng 8000 để truy cập API
EXPOSE 8000

# Lệnh chạy ứng dụng
CMD ["python", "run.py"]
